---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2008r2
    driver_config:
      box: opentable/win-2008r2-datacenter-amd64-nocm
      vm_hostname: w2012R1
      communicator: winrm
      gui: true
    transport:
      name: winrm
      provisoner:
              #require_chef_omnibus: 12.4.3
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
      vm_hostname: w2012R1
      communicator: winrm
      gui: true
    transport:
      name: winrm
      provisoner:
              #require_chef_omnibus: 12.4.3

suites:
  - name: default
    run_list:
      - recipe[bbwin::default]
    attributes:
