name 'bbwin'
maintainer 'John Smyth'
maintainer_email 'fatjohnny@wastedbandwidth.net'
license 'all_rights'
description 'Installs/Configures bbwin'
long_description 'Installs/Configures bbwin'
version '1.0.0'
